# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gosec
    - govet
    - iface
    - inamedparam
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
    nilnil:
      only-two: false
      detect-opposite: true
    nolintlint:
      require-explanation: true
      require-specific: true
    reassign:
      patterns:
        - ".*"
    revive:
      enable-default-rules: true
      rules:
        - name: context-as-argument
          arguments:
            - allow-types-before: "*testing.T"
    sloglint:
      context: all
      static-msg: true
    spancheck:
      checks:
        - end
        - record-error
        - set-status
formatters:
  enable:
    - gofmt
    - goimports
