{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ephemeral-envs.fullname" . }}
  labels:
    {{- include "ephemeral-envs.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: 
      - namespaces
    verbs: 
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ephemeral-envs.fullname" . }}
  labels:
    {{- include "ephemeral-envs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ephemeral-envs.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ephemeral-envs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}