---
apiVersion: v1
kind: Namespace
metadata:
  name: env-test-trigger-prometheus
  labels:
    envs.sberz.de/name: test-trigger-prometheus
  annotations:
    url.envs.sberz.de/api: "https://api-test-trigger-prometheus.example.com"
    url.envs.sberz.de/dashboard: "https://app-test-trigger-prometheus.example.com"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-prometheus
  namespace: env-test-trigger
  labels:
    app.kubernetes.io/name: demo-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-prometheus
    spec:
      containers:
        - name: demo
          image: docker.io/hashicorp/http-echo:latest
          ports:
            - containerPort: 5678
              name: http

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-prometheus
  namespace: env-test-trigger
spec:
  scaleTargetRef:
    name: demo-prometheus
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: demo_trigger
        query: 'time() - max(ephemeralenv_last_ignition_requested{namespace="env-test-trigger"}) < bool 60'
        threshold: "1"
