name: Release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup helm
        uses: azure/setup-helm@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sberz/ephemeral-envs
          tags: |
            type=semver,pattern={{version}},priority=900
            type=semver,pattern={{major}}.{{minor}},priority=850
            type=ref,event=branch,suffix=-{{sha}},priority=700
            type=edge,branch=main,priority=100
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Create Helm release
        run: |
          ./charts/prepare-release.sh ${{ steps.meta.outputs.version }}
          helm push charts/ephemeral-envs-*.tgz oci://ghcr.io/sberz/charts
